# Generated by Django 2.2.5 on 2019-11-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=100)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath0', models.CharField(max_length=20)),
                ('imagePath1', models.CharField(max_length=20)),
                ('imagePath2', models.CharField(blank=True, max_length=20)),
                ('imagePath3', models.CharField(blank=True, max_length=20)),
                ('imagePath4', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('body', models.CharField(max_length=20)),
                ('character0', models.CharField(default='', max_length=20)),
                ('character1', models.CharField(default='', max_length=20)),
                ('character2', models.CharField(default='', max_length=20)),
                ('blood', models.CharField(max_length=20)),
                ('smoking', models.CharField(max_length=20)),
                ('alcohol', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath0', models.CharField(max_length=255)),
                ('imagePath1', models.CharField(max_length=255)),
                ('imagePath2', models.CharField(blank=True, max_length=255)),
                ('imagePath3', models.CharField(blank=True, max_length=255)),
                ('imagePath4', models.CharField(blank=True, max_length=255)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('evaluating', models.BooleanField(default=False)),
                ('sign_success', models.BooleanField(default=False)),
                ('raters', models.TextField(blank=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('evaluating', models.BooleanField(default=False)),
                ('sign_success', models.BooleanField(default=False)),
                ('raters', models.TextField(blank=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member', to_field='email')),
            ],
        ),
    ]
