# Generated by Django 2.2.5 on 2019-11-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='female',
            name='five_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='female',
            name='four_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='female',
            name='one_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='female',
            name='three_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='female',
            name='two_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='five_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='four_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='one_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='three_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='two_point',
            field=models.IntegerField(default=0),
        ),
    ]
