# Generated by Django 2.2.5 on 2019-11-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191111_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female',
            name='evaluating',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='female',
            name='member_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_female', to='api.Member', to_field='email'),
        ),
        migrations.AlterField(
            model_name='female',
            name='raters',
            field=models.TextField(blank=True, default='|'),
        ),
        migrations.AlterField(
            model_name='male',
            name='evaluating',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='male',
            name='member_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_male', to='api.Member', to_field='email'),
        ),
        migrations.AlterField(
            model_name='male',
            name='raters',
            field=models.TextField(blank=True, default='|'),
        ),
    ]
