# Generated by Django 2.2.5 on 2019-11-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191114_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='member_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile_image', to='api.Member', to_field='email'),
        ),
    ]
