# Generated by Django 2.2.5 on 2019-11-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191114_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='female',
            name='high_s_member',
            field=models.TextField(blank=True, default='|'),
        ),
        migrations.AddField(
            model_name='female',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='high_s_member',
            field=models.TextField(blank=True, default='|'),
        ),
        migrations.AddField(
            model_name='male',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
