# Generated by Django 2.2.5 on 2019-11-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191115_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='female',
            name='average_point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='average_point',
            field=models.FloatField(default=0),
        ),
    ]
